# Generated by Django 2.2.4 on 2021-04-04 14:23

import phonenumbers
from django.db import migrations


def set_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, "RU")
        except phonenumbers.phonenumberutil.NumberParseException as e:
            print(e)
        else:
            if phonenumbers.is_valid_number(parsed_phonenumber):
                flat.owner_pure_phone = parsed_phonenumber
                flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone)
    ]
