# Generated by Django 2.2.4 on 2021-04-04 15:25

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, defaults={
            'owners_phonenumber': flat.owners_phonenumber,
            'owner_pure_phone': flat.owner_pure_phone
        })


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20210404_1823'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
